repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v2.4.0
    hooks:
    -   id: check-yaml
    -   id: end-of-file-fixer
    -   id: trailing-whitespace
    -   id: check-added-large-files
    -   id: check-merge-conflict
    -   id: flake8
-   repo: https://github.com/psf/black
    rev: 23.9.1
    hooks:
    - id: black
      language_version: python3.11
# Use autopep8 instead if `black` is too strict.
#-   repo: https://github.com/pre-commit/mirrors-autopep8
#    rev: ''  # Use the sha / tag you want to point at
#    hooks:
#    -   id: autopep8
-   repo: https://github.com/pre-commit/mirrors-isort
    rev: v5.10.1  # Use the revision sha / tag you want to point at
    hooks:
    -   id: isort
