version: '3.7'

services:
  web:
    build:
      context: .
      dockerfile: ./docker/local/web/Dockerfile
    command: /root/.local/bin/pipenv run /app/todo_everything/manage.py runserver 0.0.0.0:8000
    volumes:
      - ./todo_everything:/app/todo_everything
    ports:
      - 8000:8000
    env_file:
      - ./docker/.env.dev
