version: '3.7'

services:
  web:
    build:
      context: .
      dockerfile: docker/Dockerfile-web
    command: python todo_everything/manage.py runserver 0.0.0.0:8000
    volumes:
      - ./todo_everything:/home/webapp/todo_everything
    ports:
      - "8000:8000"
    env_file:
      - ./docker/.env.dev
    depends_on:
      - postgres
    environment:
      - DATABASE_NAME=postgres
      - DATABASE_USER=postgres
      - DATABASE_PASS=postgres
      - DATABASE_HOST=postgres
      - DATABASE_PORT=5432

  jobs:
    build:
      context: .
      dockerfile: docker/Dockerfile-web
    # IMPORTANT: Need this or else celery won't be able to figure out the Django
    #   app's paths and all the Django app's settings paths won't point to the
    #   right thing.
    working_dir: /home/webapp/todo_everything
    command: celery --app todo_everything worker -l info
    volumes:
      - ./todo_everything:/home/webapp/todo_everything
    env_file:
      - ./docker/.env.dev
    depends_on:
      - postgres
      - rabbitmq

  postgres:
    image: postgres:16-alpine
    restart: always
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres

  rabbitmq:
    image: rabbitmq:3.12.6-management
    ports:
      - "5672:5672"
      # Management UI port
      - "15672:15672"
    environment:
      - RABBITMQ_DEFAULT_USER=guest
      - RABBITMQ_DEFAULT_PASS=guest

volumes:
  pgdata:
