version: '3.7'

services:
  web:
    build:
      context: .
      dockerfile: docker/Dockerfile-web
    command: poetry run todo_everything/manage.py runserver 0.0.0.0:8000
    volumes:
      - ./todo_everything:/home/webapp/todo_everything
    ports:
      - "8000:8000"
    env_file:
      - ./docker/.env.dev
