version: '3.7'

services:
  web:
    build:
      context: .
      dockerfile: docker/Dockerfile-web
    command: poetry run todo_everything/manage.py runserver 0.0.0.0:8000
    volumes:
      - ./todo_everything:/home/webapp/todo_everything
    ports:
      - "8000:8000"
    env_file:
      - ./docker/.env.dev
    depends_on:
      - postgres

  postgres:
    image: postgres:16-alpine
    restart: always
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres

volumes:
  pgdata:
