# Generated by Django 4.2.6 on 2023-12-22 21:53

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("organizations", "0001_initial"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="organizationaccounts",
            unique_together={("organization", "account")},
        ),
    ]
