# Generated by Django 4.2.6 on 2023-12-23 06:55

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("organizations", "0002_alter_organizationaccounts_unique_together"),
    ]

    operations = [
        migrations.AddField(
            model_name="organizationaccounts",
            name="role",
            field=models.CharField(
                choices=[("admin", "Admin"), ("member", "Member"), ("guest", "Guest")],
                default="member",
                max_length=64,
            ),
        ),
        migrations.AlterField(
            model_name="organization",
            name="accounts",
            field=models.ManyToManyField(
                related_name="organizations",
                through="organizations.OrganizationAccounts",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
