# pull official base image
FROM python:3.11-slim-bullseye

RUN useradd --create-home webapp

# set work directory
WORKDIR /home/webapp

# set environment variables
ENV PYTHONDONTWRITEBYTECODE 1
ENV PYTHONUNBUFFERED 1

# install dependencies
RUN pip3 install --upgrade pip
RUN pip3 install poetry

# Install poetry
#RUN pip install --user poetry
#COPY ./docker/get-poetry.py .
#RUN python get-poetry.py -y
ENV PATH="${PATH}:/home/webapp/.local/bin"

COPY poetry.lock .
COPY pyproject.toml .
COPY pytest.ini .
RUN poetry --version
RUN poetry config virtualenvs.create false --local
RUN set -ex && poetry install --no-interaction --no-root --no-ansi
RUN chown webapp:webapp poetry*

USER webapp

# copy project
# COPY ../todo_everything /usr/src/app/
