# Generated by Django 3.0.2 on 2020-01-12 06:36

import todo_everything.apps.accounts.managers
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelManagers(
            name="account",
            managers=[
                ("objects", todo_everything.apps.accounts.managers.AccountManager()),
            ],
        ),
    ]
