name: Lint

on: [pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Install Python
        # https://github.com/actions/setup-python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11.5'
      - name: Get changed files
        id: changed-files
        uses: tj-actions/changed-files@v35
        with:
          files: '**/*.py'
      - name: Install poetry
        uses: abatilo/actions-poetry@v2
      - name: Setup a local virtual environment (if no poetry.toml file)
        run: |
          poetry config virtualenvs.create true --local
          poetry config virtualenvs.in-project true --local
      - uses: actions/cache@v3
        name: Define a cache for the virtual environment based on the dependencies lock file
        with:
          path: ./.venv
          key: venv-${{ hashFiles('poetry.lock') }}
      - name: Install the project dependencies
        run: poetry install
      - name: Run linters
        run: poetry run pre-commit run --files ${{ steps.changed-files.outputs.all_changed_files }}
